server:
  port: 9411
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.174.226/maple?characterEncoding=utf-8
    username: root
    password: Dfas528811729!
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
    host: 47.96.174.226
    port: 6379
    password: dfas6485751
    database: 0
    pool:
      max-active: 8
      min-idle: 0  # 连接池中的最小空闲连接
      max-wait: -1 # 连接超时时间（毫秒）
      max-idle: 8
  application:
    name: zipkin
  rabbitmq:
    host: 47.96.174.226
    port: 5672
    username: guest
    password: guest
#feign 断路器