eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8093
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.174.226/maple?characterEncoding=utf-8
    username: root
    password: Dfas528811729!
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true